### ISSUE TITLE
Styling links (e.g. Block Link) in next.js

### ISSUE THREAD

**Issue by easherma** [state-matters/web#19]
In the previous repo, we used the TouchTarget component to create and style many of the links on the site. This component does not port over cleanly since:

a) it uses 'theme' instead of constant (which is annoying but not a deal breaker)
b) it relies on importing Link from react-router-dom, which we aren't using anymore

I tried swapping out "next/link" for "react-router-dom", but that seemed to cause problems with creating the component (or maybe with styled-components? the error messages were not clear to me).

**Comment by pkrawc** [comment]
Totes. It's cause links in next just decorate their child node. It'll just take changing the link to render both a next link and a child a tag and then the children.
