### ISSUE TITLE
Facebook is complaining about GZIP issues on production site.

### ISSUE THREAD

**Issue by pkrawc** [state-matters/web#26]
Using this tool: https://developers.facebook.com/tools/debug/sharing/

The sharing works perfectly when you use a URL straight from now.

https://state-matters-khghkenn9.now.sh/ilinformed

But the debugger yells at you when using the production site (which should be aliased to the exact same thing as the url above)

https://www.statematters.org/ilinformed

@easherma i'd really appreciate it if you could either rule this as unimportant or try and problem solve a bit.

**Comment by pkrawc** [comment]
It is actually working when I try and post it to facebook though. So I'm leaning towards calling this a non-issue @easherma .

**Comment by easherma** [comment]
I'm not seeing that issue in particular when I use the debugger. Since preview links are working, lets close and re-open if it turns out to be a problem later.
